name: Deploy Student App

on:
  push:
    branches:
      - main   # or your deploy branch
      - staging
    paths:
      - 'students/**'   # only run when student app changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    
      # Pick environment based on the branch
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./students

      - name: Build project
        run: pnpm run build
        working-directory: ./students
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_CALLBACK_URL: ${{ vars.VITE_CALLBACK_URL }}
          VITE_API_TIMEOUT: ${{ vars.VITE_API_TIMEOUT }}
          VITE_NODE_ENV: ${{ vars.VITE_NODE_ENV }}

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./students/dist/
          server-dir: /students/   # adjust if needed
